language: node_js
node_js:
  - 5.6
before_script:
  - gem install percy-cli
after_success:
  - '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && npm run perceptual-diff'
sudo: false
deploy:
  provider: script
  script: echo "npm credentials were revoked on 2018-07-12. We regenerated many
    credentials, but this repository had no changes in at least 18 months and
    was skipped. Reconfigure npm deployments. -omsmith"; exit 1
  on:
    tags: true
    all_branches: true
env:
  global:
    secure: BqFz4jf6AMv/XC4QtELy9LxsrHmQmW8pmyZt7kGb/C6Xz7l8WtGnRjrZ7DB2pC1sUPnkc5cwf33pUyOWSNvtlc2gnHi0h7SdirDnWOtpbTA1XAGm2N6anQ7BktfPXmEtYqn3BCaoKnMYCoCvGr+1lvRahYzFIpajDht2k/lprvs=
