language: node_js
node_js:
- 5.6
sudo: false
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: MXtjtXFLjnjcRwPL613K3AWjAgnQmpvQA9Fj0C26/H7GWF5VZ0IyBf3/2NozZWGtICk8sttLeHcgQtwX5ZNMN7tqDcbkgsgD9lAHWsvYTR9hKs3LQaxK+YroHcDfaH5LylO5CkxeNfbM+BEqnnybxMIfSP2I3WqcIK1sULPqNpc=
  on:
    tags: true
    all_branches: true
